//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFood.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IngredientReteta", Namespace="http://schemas.datacontract.org/2004/07/ValoriNutritionale")]
    [System.SerializableAttribute()]
    public partial class IngredientReteta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CaloriiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CarbohidratiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GrasimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ProteineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Calorii {
            get {
                return this.CaloriiField;
            }
            set {
                if ((this.CaloriiField.Equals(value) != true)) {
                    this.CaloriiField = value;
                    this.RaisePropertyChanged("Calorii");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Carbohidrati {
            get {
                return this.CarbohidratiField;
            }
            set {
                if ((this.CarbohidratiField.Equals(value) != true)) {
                    this.CarbohidratiField = value;
                    this.RaisePropertyChanged("Carbohidrati");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Grasimi {
            get {
                return this.GrasimiField;
            }
            set {
                if ((this.GrasimiField.Equals(value) != true)) {
                    this.GrasimiField = value;
                    this.RaisePropertyChanged("Grasimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Proteine {
            get {
                return this.ProteineField;
            }
            set {
                if ((this.ProteineField.Equals(value) != true)) {
                    this.ProteineField = value;
                    this.RaisePropertyChanged("Proteine");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        private double p1;
        private double p2;
        private double p3;
        private double p4;

        public IngredientReteta(double p1, double p2, double p3, double p4)
        {
            // TODO: Complete member initialization
            this.p1 = p1;
            this.p2 = p2;
            this.p3 = p3;
            this.p4 = p4;
        }

        public IngredientReteta()
        {
            // TODO: Complete member initialization
        }
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="ServiceReference2.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/AdunaIngrediente", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/AdunaIngredienteResponse")]
        EasyFood.ServiceReference2.IngredientReteta AdunaIngrediente(EasyFood.ServiceReference2.IngredientReteta[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/AdunaIngrediente", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/AdunaIngredienteResponse")]
        System.Threading.Tasks.Task<EasyFood.ServiceReference2.IngredientReteta> AdunaIngredienteAsync(EasyFood.ServiceReference2.IngredientReteta[] arr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/ImparteIngredient", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/ImparteIngredientResponse")]
        EasyFood.ServiceReference2.IngredientReteta ImparteIngredient(EasyFood.ServiceReference2.IngredientReteta ingr, double nrGrame);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/ImparteIngredient", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/ImparteIngredientResponse")]
        System.Threading.Tasks.Task<EasyFood.ServiceReference2.IngredientReteta> ImparteIngredientAsync(EasyFood.ServiceReference2.IngredientReteta ingr, double nrGrame);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : EasyFood.ServiceReference2.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<EasyFood.ServiceReference2.ICalculator>, EasyFood.ServiceReference2.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EasyFood.ServiceReference2.IngredientReteta AdunaIngrediente(EasyFood.ServiceReference2.IngredientReteta[] arr) {
            return base.Channel.AdunaIngrediente(arr);
        }
        
        public System.Threading.Tasks.Task<EasyFood.ServiceReference2.IngredientReteta> AdunaIngredienteAsync(EasyFood.ServiceReference2.IngredientReteta[] arr) {
            return base.Channel.AdunaIngredienteAsync(arr);
        }
        
        public EasyFood.ServiceReference2.IngredientReteta ImparteIngredient(EasyFood.ServiceReference2.IngredientReteta ingr, double nrGrame) {
            return base.Channel.ImparteIngredient(ingr, nrGrame);
        }
        
        public System.Threading.Tasks.Task<EasyFood.ServiceReference2.IngredientReteta> ImparteIngredientAsync(EasyFood.ServiceReference2.IngredientReteta ingr, double nrGrame) {
            return base.Channel.ImparteIngredientAsync(ingr, nrGrame);
        }
    }
}
