// <auto-generated />
namespace EasyFood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BD6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BD6));
        
        string IMigrationMetadata.Id
        {
            get { return "201905121428530_BD6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
